### PR TITLE
Melvin-Datapackageblog

### PR DESCRIPTION
**Pull request by IamMelvin5**
# Overview

Blog on data package creation

### CODE REVIEW

**Review by lwinfree — CHANGES_REQUESTED** [review]
Hi @IamMelvin5 ! Thanks for adding your blog! It looks good overall 😃 There are some changes that you should make:

- the title has a typo: "Dta" instead of "Data"
- please change all your H1 levels to H2 (change all your '#' to '##')
- can you please add all your images as separate files and then change the image markdown syntax to html? (so, replace `error` with `error` This needs to happen because the images are HUGE when they are displayed via markdown.

That's it! Let me know if you have any issues -- Thanks!

**Comment by IamMelvin5** [comment]
Hi LIly,
Hope you are having a good start for the week. I'm working on the changes
above but I've realised for the images if I use( Validate
I'm able to see the image in the preview, however if I use validate
I only see a tiny image icon. Kindly advise me on how best to do it. Thank
you.

Kind regards,
Melvin.

**Comment by lwinfree** [comment]
Hi @IamMelvin5 ! Please use the html (the bit starting with `<img`...) but replace the image source (`src="image-file"`) with your image file. You will need to upload the image files as well. You can add the files directly to this folder, and make sure that your image file name matches what you have written in html source. Does that make sense?

**Comment by lwinfree** [comment]
fixed & closed by #174

**Pull request closed without merging**
