### PR TITLE
First blog draft post

### PR DESCRIPTION
**Pull request by ritwikagarwal**
# Overview

Introductory blog post for ritwik

---

Please preserve this line to notify @lwinfree (lead of this repository)

### CODE REVIEW

**Comment by lwinfree** [comment]
Hi @ritwikagarwal! This is looking pretty good, but there are a few changes that you need to make before I can merge this. 
The first is that the publication date is in the wrong format. It should be year-month-day (so, 2020-08-29). 
The other thing is that you haven't added a picture or avatar. Please add your picture/avatar as a separate file within your blog's folder, and also add the file name within the blog text at the bottom (where it says `subject_img: your-picture.jpg` replace `your-picture.jpg` with the name of your picture/avatar.
Also, I see that I misspelled your name on your blog's folder, so I will fix that (sorry!!).

**Comment by ritwikagarwal** [comment]
Done with edits

**Comment by lwinfree** [comment]
hi @ritwikagarwal! Thanks for the edits, but there are still some issues to fix. The first is that the date needs to have dashes `-` instead of slashes `/`, so it should be `2020-08-29` instead of `2020/08/29`. The second is that you still need to add your image to the blog folder. Does that all make sense?

**Comment by lwinfree** [comment]
thanks @ritwikagarwal! I'll merge now 😃

**Pull request merged**
