### PR TITLE
Datapackaging-Scientometrics

### PR DESCRIPTION
**Pull request by sarenaz**
# Overview

Please replace this line with full information about your pull request. Make sure that tests pass before publishing it

### CODE REVIEW

**Review by lwinfree — CHANGES_REQUESTED** [review]
hi @sarenaz your blog is good! I like the information and the way you explain things. But, the images aren't displaying. I think you forgot to upload the images here? Can you please add them and then I will merge. Thanks!

**Comment by sarenaz** [comment]
hi @lwinfree thank you for this note. i've added the missed images. hopefully, this time successfully.

**Review by lwinfree — APPROVED** [review]
Thanks for adding the pics! They were really small, so I changed their width from '70' to '100%'. I also removed the table from the last 2 images since it was making them too small to really see. Hope that is OK!

**Comment by sarenaz** [comment]
Hello, Lilly. Thank you very much for changes; they're absolutely OK for me. Appreciated.

**Pull request merged**
