### PR TITLE
first draft of introductory blog post

### PR DESCRIPTION
**Pull request by jmaasch**
# Overview

Pull request for rough draft of intro blog post.

---

Please preserve this line to notify @lwinfree (lead of this repository)

### CODE REVIEW

**Comment by lwinfree** [comment]
hey @jmaasch :-) I am not going to review this yet, as I am pretty sure there were some edits you still wanted to make. Tag me in a comment here when you are ready for me to take a look!

**Comment by jmaasch** [comment]
@lwinfree I have updated the blog and added my photo. This should be its final form. Let me know if there are any issues :)

**Comment by lwinfree** [comment]
hi @jmaasch this looks good! I am going to make one change, which is the format for the publication date. It needs to be YYYY-MM-DD, so I can change it.

**Comment by jmaasch** [comment]
@lwinfree Thanks Lilly!

**Pull request merged**
